### ISSUE TITLE
What data is available for socioeconomic level?

### ISSUE THREAD

**Issue by machallboyd** [machallboyd/restaurant-grocery-socioeconomic#2]
What data can we get for "how well-off is an area?" There's probably reams of work done on this already, but the two ideas we've thrown out so far are

- Income data by census
- Restaurant price for an area by google api

At the moment, we're thinking of letting the user toggle through different ways to measure this.

**Comment by anneet** [comment]
found a site that can use zipcode and tract
https://data.census.gov/table?g=1400000US06001410500_860XX00US94612&tid=ACSST5Y2021.S1901

**Comment by anneet** [comment]
https://abc7news.com/food-desert-bay-area-deserts-pantry-near-me-alameda-bank/11254529/

**Comment by anneet** [comment]
For restaurant, we can use the price_level outline here:
https://developers.google.com/maps/documentation/places/web-service/details 

And geocode for zipcode
