### ISSUE TITLE
What data is available for food availability?

### ISSUE THREAD

**Issue by machallboyd** [machallboyd/restaurant-grocery-socioeconomic#3]
What data can we scrape for measurements of food availability? At the moment, we're assuming we can measure the amount of grocery stores in a specific area via the Google Maps api.

At this stage, we're more worried about ingesting data rather than how to analyze it, but we're collecting with an eye towards later analyzation issues. Does the quality of the grocery store matter? For instance, is a place with lots of expensive restaurants and one Whole Foods a food desert? Do we also need to approximate how easy it might be to get to the grocery store?

**Comment by anneet** [comment]
Places API is what we are looking for:
https://developers.google.com/maps/documentation/places/web-service/overview

We should be able to use it to separate restaurants from grocery stores and see the price levels of both

**Comment by anneet** [comment]
I did notice that while looking on google maps myself some convenance stores and small markets are counted as grocery stores. It seems that while their category is "Liquor store" they may also be marked as "grocery stores" but we'd have to play with the API to see.

**Comment by machallboyd** [comment]
It might be interesting to have a count of the dollar stores that replace
more well regarded grocery stores.
